export const locationLabels: Record<string, string> = {
    KellerHall: "Keller Hall",
    MooreHall: "Moore Hall",
    ArchitectureSchool: "Architecture School",
    AgriculturalScience: "Agricultural Science",
    ArtBuilding: "Art Building",
    BachmanHall: "Bachman Hall",
    BilgerHall: "Bilger Hall",
    BiomedicalSciences: "Biomedical Sciences",
    BurnsHall: "Burns Hall",
    CenterforKoreanStudies: "Center for Korean Studies",
    CrawfordHall: "Crawford Hall",
    DanceBuilding: "Dance Building",
    DeanHall: "Dean Hall",
    EdmondsonHall: "Edmondson Hall",
    FrearHall: "Frear Hall",
    GartleyHall: "Gartley Hall",
    GeorgeHall: "George Hall",
    GilmoreHall: "Gilmore Hall",
    HawaiiHall: "Hawaii Hall",
    HemenwayHall: "Hemenway Hall",
    HenkeHall: "Henke Hall",
    HolmesHall: "Holmes Hall",
    InformationTechnologyCenter: "Information Technology Center",
    JeffersonHall: "Jefferson Hall",
    JohnsonHall: "Johnson Hall",
    JohnABurnsSchoolofMedicine: "John A. Burns School of Medicine",
    KamakakuokalaniCenterforHawaiianStudies: "Kamakakūokalani Center for Hawaiian Studies",
    KennedyTheatre: "Kennedy Theatre",
    KraussHall: "Krauss Hall",
    KuykendallHall: "Kuykendall Hall",
    LawSchool: "Law School",
    LincolnHall: "Lincoln Hall",
    MarineSciencesBuilding: "Marine Sciences Building",
    MillerHall: "Miller Hall",
    MusicBuildingComplex: "Music Building Complex",
    PacificBiosciencesResearchCenter: "Pacific Biosciences Research Center",
    PacificOceanScienceandTechnology: "Pacific Ocean Science and Technology",
    PhysicalPlantBuilding: "Physical Plant Building",
    PhysicalScienceBuilding: "Physical Science Building",
    PopeLaboratory: "Pope Laboratory",
    SakamakiHall: "Sakamaki Hall",
    SaundersHall: "Saunders Hall",
    ShermanLaboratory: "Sherman Laboratory",
    ShidlerCollegeofBusiness: "Shidler College of Business",
    SnyderHall: "Snyder Hall",
    SpaldingHall: "Spalding Hall",
    StJohnPlantScienceLab: "St. John Plant Science Lab",
    WatanabeHall: "Watanabe Hall",
    WebsterHall: "Webster Hall",
    Other: "Other",
  };